# Stage 1: Build the Angular application
FROM node:20 as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:1.21.1 as serve
COPY --from=build /app/dist/dynamic-needs-analysis /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf