version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dynamic-needs-analysis-dev
    container_name: dynamic-needs-analysis-dev-container
    ports:
      - 4200:4200
    volumes:
      - ./src:/app/src
    command: npm run docker-dev